torch 복습을 위한 정리일 뿐. 이론을 보기 위해선 2021년도 12월 torch 정리본을 봐야함

In [3]:
import torch


In [5]:

x = torch.empty(4,2)


In [6]:
print(x)    
print(x.size())

tensor([[0.0000e+00, 4.3009e-05],
        [6.6283e-10, 8.3191e+20],
        [8.1993e-10, 1.6618e+22],
        [1.0257e-08, 2.6515e-09]])
torch.Size([4, 2])


In [7]:
x = torch.randn(4,5)
y = x.view(20)
z = x.view(5,-1)

print(x)
print(y)
print(z)

tensor([[ 0.7581,  0.6066,  0.4107,  1.1026, -0.1340],
        [-0.9506, -0.9405,  1.3187, -0.6474,  1.5503],
        [-0.3225,  0.1542, -1.1971, -1.0386, -2.1580],
        [-1.1001, -1.4447, -0.9596, -0.5740, -0.0070]])
tensor([ 0.7581,  0.6066,  0.4107,  1.1026, -0.1340, -0.9506, -0.9405,  1.3187,
        -0.6474,  1.5503, -0.3225,  0.1542, -1.1971, -1.0386, -2.1580, -1.1001,
        -1.4447, -0.9596, -0.5740, -0.0070])
tensor([[ 0.7581,  0.6066,  0.4107,  1.1026],
        [-0.1340, -0.9506, -0.9405,  1.3187],
        [-0.6474,  1.5503, -0.3225,  0.1542],
        [-1.1971, -1.0386, -2.1580, -1.1001],
        [-1.4447, -0.9596, -0.5740, -0.0070]])


In [10]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.7044])
-0.7044336795806885
torch.float32
